Instance: BundleStructuredData
InstanceOf: CHCRLBundle
Title: "BundleStructuredData"
Description: "Example for Bundle"
Usage: #example
* meta.lastUpdated = "2019-11-05T12:02:50.958+00:00"
* identifier.system = "http://example.fhir"
* identifier.value = "1234"
* type = #document
* timestamp = "2019-11-05T12:02:50.958+00:00"
* entry[0].fullUrl = "http://test.fhir.ch/r4/Composition/CompStructuredData"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-1
* entry[+].fullUrl = "http://test.fhir.ch/r4/Patient/FranzMinimum"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-2
* entry[+].fullUrl = "http://test.fhir.ch/r4/Communication/CommMinimum"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-3
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/ConcomitantDiseaseA"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-4
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/ConcomitantDiseaseB"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-5
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/FinalCauseOfDeath"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-6
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/PrimaryDisease"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-7
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/SecondaryDisease"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-8
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/a-PrefixOfpTNM"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-9
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/DateOfIncidence"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-10
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/ICD-10"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-11
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/ICD-O-3-Behaviour"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-12
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/ICD-O-3-Laterality"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-13
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/ICD-O-3-Morphology"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-14
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/ICD-O-3-Topography"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-15
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/LymphaticInvasion"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-16
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/m-SuffixOfpT"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-17
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/NumberExaminedRegionalLymphNodes"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-18
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/NumberInvolvedRegionalLymphNodes"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-19
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/PerineuralInvasion"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-20
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/TNM-StageGroup"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-21
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/VenousInvasion"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-22
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/y-PrefixOfcTNM"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-23
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/y-PrefixOfpTNM"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-24
* entry[+].fullUrl = "http://test.fhir.ch/r4/Procedure/DiagnosticMethod"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-25
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/ICD-O-3-HistologicalGrade-unknown"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-26
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/AbteilungMinimum"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-27
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/cM"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-28
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/cN"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-29
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/cT"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-30
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/pM-unknown"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-31
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/pN"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-32
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/pT"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-33
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/SpitalMinimum"
* entry[=].resource = Inline-Instance-for-BundleStructuredData-34