@host = http://test.fhir.ch/r4

###
PUT {{host}}/Patient/FranzMinimum HTTP/1.1
Content-Type: application/fhir+xml

< ./patient/FranzMinimum.xml

###
PUT {{host}}/Patient/RobertMeier HTTP/1.1
Content-Type: application/fhir+xml

< ./patient/RobertMeier.xml


###
PUT {{host}}/Practitioner/AgnesBauer HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/AgnesBauer.xml

###
PUT {{host}}/Practitioner/EmmaMinimum HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/EmmaMinimum.xml


###
PUT {{host}}/Organization/SpitalMinimum HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/SpitalMinimum.xml

###
PUT {{host}}/Organization/SpitalSeeblickDoktorGastro HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/SpitalSeeblickDoktorGastro.xml

###
PUT {{host}}/Organization/SpitalSeeblickDoktorPatho HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/SpitalSeeblickDoktorPatho.xml

###
PUT {{host}}/Organization/SpitalSeeblickHansEgli HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/SpitalSeeblickHansEgli.xml

###
PUT {{host}}/Organization/AbteilungGastro HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/AbteilungGastro.xml

###
PUT {{host}}/Organization/AbteilungMinimum HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/AbteilungMinimum.xml

###
PUT {{host}}/Organization/AbteilungOnko HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/AbteilungOnko.xml

###
PUT {{host}}/Organization/AbteilungPatho HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/AbteilungPatho.xml


###
PUT {{host}}/DocumentReference/DocuHospMinimum HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocuHospMinimum.xml

###
PUT {{host}}/DocumentReference/DocuPractMinimum HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocuPractMinimum.xml

###
PUT {{host}}/DocumentReference/DocuUC1aGastro20181201 HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocuUC1aGastro20181201.xml

###
PUT {{host}}/DocumentReference/DocuUC1aInfo20181207 HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocuUC1aInfo20181207.xml

###
PUT {{host}}/DocumentReference/DocuUC1aOps20181214 HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocuUC1aOps20181214.xml

###
PUT {{host}}/DocumentReference/DocuUC1aPatho20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocuUC1aPatho20181202.xml

###
PUT {{host}}/DocumentReference/DocuUC1aPatho20181215 HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocuUC1aPatho20181215.xml


###
PUT {{host}}/Communication/CommMeier HTTP/1.1
Content-Type: application/fhir+xml

< ./communication/CommMeier.xml

###
PUT {{host}}/Communication/CommMinimum HTTP/1.1
Content-Type: application/fhir+xml

< ./communication/CommMinimum.xml


###
PUT {{host}}/Condition/ConcomitantDiseaseA HTTP/1.1
Content-Type: application/fhir+xml

< ./condition/ConcomitantDiseaseA.xml

###
PUT {{host}}/Condition/ConcomitantDiseaseB HTTP/1.1
Content-Type: application/fhir+xml

< ./condition/ConcomitantDiseaseB.xml

###
PUT {{host}}/Condition/FinalCauseOfDeath HTTP/1.1
Content-Type: application/fhir+xml

< ./condition/FinalCauseOfDeath.xml

###
PUT {{host}}/Condition/PrimaryDisease HTTP/1.1
Content-Type: application/fhir+xml

< ./condition/PrimaryDisease.xml

###
PUT {{host}}/Condition/SecondaryDisease HTTP/1.1
Content-Type: application/fhir+xml

< ./condition/SecondaryDisease.xml


###
PUT {{host}}/Observation/a-PrefixOfpTNM-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/a-PrefixOfpTNM-20181202.xml

###
PUT {{host}}/Observation/a-PrefixOfpTNM HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/a-PrefixOfpTNM.xml

###
PUT {{host}}/Observation/cM-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/cM-20181202.xml

###
PUT {{host}}/Observation/cM HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/cM.xml

###
PUT {{host}}/Observation/cN-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/cN-20181202.xml

###
PUT {{host}}/Observation/cN HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/cN.xml

###
PUT {{host}}/Observation/cT-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/cT-20181202.xml

###
PUT {{host}}/Observation/cT HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/cT.xml

###
PUT {{host}}/Observation/DateOfIncidence-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/DateOfIncidence-20181202.xml

###
PUT {{host}}/Observation/DateOfIncidence HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/DateOfIncidence.xml

###
PUT {{host}}/Observation/ICD-10-Kolon20181201 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-10-Kolon20181201.xml

###
PUT {{host}}/Observation/ICD-10-Kolon20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-10-Kolon20181202.xml

###
PUT {{host}}/Observation/ICD-10 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-10.xml

###
PUT {{host}}/Observation/ICD-O-3-Behaviour-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-O-3-Behaviour-20181202.xml

###
PUT {{host}}/Observation/ICD-O-3-Behaviour HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-O-3-Behaviour.xml

###
PUT {{host}}/Observation/ICD-O-3-HistologicalGrade-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-O-3-HistologicalGrade-20181202.xml

###
PUT {{host}}/Observation/ICD-O-3-HistologicalGrade-unknown HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-O-3-HistologicalGrade-unknown.xml

###
PUT {{host}}/Observation/ICD-O-3-Laterality-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-O-3-Laterality-20181202.xml

###
PUT {{host}}/Observation/ICD-O-3-Laterality HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-O-3-Laterality.xml

###
PUT {{host}}/Observation/ICD-O-3-Morphology-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-O-3-Morphology-20181202.xml

###
PUT {{host}}/Observation/ICD-O-3-Morphology HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-O-3-Morphology.xml

###
PUT {{host}}/Observation/ICD-O-3-Topography-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-O-3-Topography-20181202.xml

###
PUT {{host}}/Observation/ICD-O-3-Topography HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/ICD-O-3-Topography.xml

###
PUT {{host}}/Observation/LymphaticInvasion-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/LymphaticInvasion-20181202.xml

###
PUT {{host}}/Observation/LymphaticInvasion HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/LymphaticInvasion.xml

###
PUT {{host}}/Observation/m-SuffixOfpT-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/m-SuffixOfpT-20181202.xml

###
PUT {{host}}/Observation/m-SuffixOfpT-unknown HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/m-SuffixOfpT-unknown.xml

###
PUT {{host}}/Observation/m-SuffixOfpT-unspecified HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/m-SuffixOfpT-unspecified.xml

###
PUT {{host}}/Observation/m-SuffixOfpT HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/m-SuffixOfpT.xml

###
PUT {{host}}/Observation/NumberExaminedRegionalLymphNodes-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/NumberExaminedRegionalLymphNodes-20181202.xml

###
PUT {{host}}/Observation/NumberExaminedRegionalLymphNodes-unknown HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/NumberExaminedRegionalLymphNodes-unknown.xml

###
PUT {{host}}/Observation/NumberExaminedRegionalLymphNodes HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/NumberExaminedRegionalLymphNodes.xml

###
PUT {{host}}/Observation/NumberInvolvedRegionalLymphNodes-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/NumberInvolvedRegionalLymphNodes-20181202.xml

###
PUT {{host}}/Observation/NumberInvolvedRegionalLymphNodes-unknown HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/NumberInvolvedRegionalLymphNodes-unknown.xml

###
PUT {{host}}/Observation/NumberInvolvedRegionalLymphNodes HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/NumberInvolvedRegionalLymphNodes.xml

###
PUT {{host}}/Observation/PerineuralInvasion-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/PerineuralInvasion-20181202.xml

###
PUT {{host}}/Observation/PerineuralInvasion HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/PerineuralInvasion.xml

###
PUT {{host}}/Observation/pM-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/pM-20181202.xml

###
PUT {{host}}/Observation/pM-unknown HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/pM-unknown.xml

###
PUT {{host}}/Observation/pN-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/pN-20181202.xml

###
PUT {{host}}/Observation/pN HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/pN.xml

###
PUT {{host}}/Observation/pT-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/pT-20181202.xml

###
PUT {{host}}/Observation/pT HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/pT.xml

###
PUT {{host}}/Observation/TNM-StageGroup-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/TNM-StageGroup-20181202.xml

###
PUT {{host}}/Observation/TNM-StageGroup HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/TNM-StageGroup.xml

###
PUT {{host}}/Observation/VenousInvasion-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/VenousInvasion-20181202.xml

###
PUT {{host}}/Observation/VenousInvasion HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/VenousInvasion.xml

###
PUT {{host}}/Observation/y-PrefixOfcTNM-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/y-PrefixOfcTNM-20181202.xml

###
PUT {{host}}/Observation/y-PrefixOfcTNM HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/y-PrefixOfcTNM.xml

###
PUT {{host}}/Observation/y-PrefixOfpTNM-20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/y-PrefixOfpTNM-20181202.xml

###
PUT {{host}}/Observation/y-PrefixOfpTNM HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/y-PrefixOfpTNM.xml


###
PUT {{host}}/Procedure/DiagnosticMethod-Biopsy20181201 HTTP/1.1
Content-Type: application/fhir+xml

< ./procedure/DiagnosticMethod-Biopsy20181201.xml

###
PUT {{host}}/Procedure/DiagnosticMethod-Biopsy20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./procedure/DiagnosticMethod-Biopsy20181202.xml

###
PUT {{host}}/Procedure/DiagnosticMethod-Endoscopy20181201 HTTP/1.1
Content-Type: application/fhir+xml

< ./procedure/DiagnosticMethod-Endoscopy20181201.xml

###
PUT {{host}}/Procedure/DiagnosticMethod-Endoscopy20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./procedure/DiagnosticMethod-Endoscopy20181202.xml

###
PUT {{host}}/Procedure/DiagnosticMethod HTTP/1.1
Content-Type: application/fhir+xml

< ./procedure/DiagnosticMethod.xml


###
PUT {{host}}/Composition/CompFromOrganization HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/CompFromOrganization.xml

###
PUT {{host}}/Composition/CompFromPractitioner HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/CompFromPractitioner.xml

###
PUT {{host}}/Composition/CompStructuredData HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/CompStructuredData.xml

###
PUT {{host}}/Composition/CompUC1aGastro20181201 HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/CompUC1aGastro20181201.xml

###
PUT {{host}}/Composition/CompUC1aInfo20181207 HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/CompUC1aInfo20181207.xml

###
PUT {{host}}/Composition/CompUC1aOps20181214 HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/CompUC1aOps20181214.xml

###
PUT {{host}}/Composition/CompUC1aPatho20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/CompUC1aPatho20181202.xml

###
PUT {{host}}/Composition/CompUC1aPatho20181215 HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/CompUC1aPatho20181215.xml

###
PUT {{host}}/Composition/CompUC1bGastro20181201 HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/CompUC1bGastro20181201.xml

###
PUT {{host}}/Composition/CompUC1bPatho20181202 HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/CompUC1bPatho20181202.xml


###
GET {{host}}/Patient/FranzMinimum HTTP/1.1
Content-Type: application/fhir+xml


###
GET {{host}}/Composition/CompFromOrganization/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/CompFromPractitioner/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/CompStructuredData/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/CompUC1aGastro20181201/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/CompUC1aInfo20181207/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/CompUC1aOps20181214/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/CompUC1aPatho20181202/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/CompUC1aPatho20181215/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/CompUC1bGastro20181201/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/CompUC1bPatho20181202/$document HTTP/1.1
Content-Type: application/fhir+xml